apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp-route
  namespace: kube-system
spec:
  parentRefs:
  - name: cluster-gateway-gateway
    namespace: envoy-gateway-system
  hostnames:
    - "headlamp-senai.com"
  rules:
  - backendRefs:
    - name: my-headlamp
      port: 80