# /grupo-01/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grupo-betinho # Força tudo deste grupo a ir para este namespace

resources:
  - webapp-deployment.yaml
  - webapp-service.yaml
  - webapp-httproute.yaml